### ISSUE TITLE
Pipeline’s Need a Time-out

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/harvey#22]
It’s possible that users can add a rogue script in the testing stage that runs forever tying up resources or that certain build stages could run too long. Add a timeout for each stage that will exit the pipeline if exceeded.

**Comment by BElluu** [comment]
Hi! Can I try deal with that issue? If yes,, do you think **multiprocessing.Process** will be ok for that?
https://stackoverflow.com/questions/492519/timeout-on-a-function-call

**Comment by Justintime50** [comment]
Hey @BElluu, we already have a timeout on suprocesses (eg: https://github.com/Justintime50/harvey/blob/master/harvey/git.py#L32); this issue is referring to pipeline's as a whole. Adding a timeout to the stage specifically would mean that tests in Docker could only run for a maximum of say 30 minutes. Currently, a pipeline can run forever if not handled properly which is why we want to correct this.

You are more than welcome to attempt a fix here and attach a PR if you'd like! Just want to clarify that the timeout is for the pipeline and not the subprocess.
